# Generated by Django 3.2.7 on 2021-09-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_site', '0002_auto_20210920_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
