# Generated by Django 3.2.7 on 2021-09-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_site', '0004_auto_20210920_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценка'),
        ),
    ]
