# Generated by Django 3.2.7 on 2021-09-20 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics_site', '0005_auto_20210921_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comics',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comics',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comics',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
