# Generated by Django 3.2.7 on 2021-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_site', '0007_auto_20210921_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comics',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
