# Generated by Django 3.2.7 on 2021-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_site', '0008_auto_20210922_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
