# Generated by Django 3.2.7 on 2021-09-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_site', '0009_alter_comics_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comics',
            new_name='Comic',
        ),
    ]
